[platformio]
default_envs = esp32dev
data_dir = data

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.filesystem = littlefs
monitor_speed = 115200
lib_deps =
  bblanchon/ArduinoJson @ ^6.21.5
  bbx10/DNSServer @ ^1.1.0
  lsatan/SmartRC-CC1101-Driver-Lib @ ^2.5.7
  links2004/WebSockets @ ^2.6.1
